#!/bin/bash

# Generate candidates.txt
cat votes.csv | \
    sed "s/,/\n/g" | \
    sed "/^$/d" | \
    sort | \
    uniq > candidates.txt

# Generate votes.txt
(
    cat candidates.txt | \
        nl | \
        sed -r 's/^ *([0-9]+)\t(.*)/s\/(^|,)\2(,|$)\/\\1\1\\2\/g/g'
) | sed -r -f /dev/stdin votes.csv | \
    sed "s/ //g" | \
    sed "s/,/ /g" > votes.txt
